services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    depends_on:
      - mongo

  worker:
    build: ./worker
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - api